# Lesson 07. Тема “Введение в линейную алгебру”

In [50]:
import numpy as np 
import matplotlib.pyplot as plt
import scipy 
import scipy.linalg  

## 5.1.
Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.


$$
 \begin{bmatrix}
  1 & 2 & 3 \\
  4 & 0 & 6 \\
  7 & 8 & 9
 \end{bmatrix}
+
 \begin{bmatrix}
  1 & 2 & 9 \\
  3 & 1 & 5 \\
  3 & 2 & 8
 \end{bmatrix}
=
 \begin{bmatrix}
  2 & 4 & 12 \\
  7 & 1 & 11 \\
  10 & 10 & 17
 \end{bmatrix}
$$

$$
 \begin{bmatrix}
  1 & 2 & 3 \\
  4 & 0 & 6 \\
  7 & 8 & 9
 \end{bmatrix}
-
 \begin{bmatrix}
  1 & 2 & 9 \\
  3 & 1 & 5 \\
  3 & 2 & 8
 \end{bmatrix}
=
 \begin{bmatrix}
  0 & 0 & -6 \\
  1 & -1 & 1 \\
  4 & 6 & 1
 \end{bmatrix}
$$

$$
 \begin{bmatrix}
  1 & 2 \\
  4 & 0 \\
  7 & 8 
 \end{bmatrix}
\times
 \begin{bmatrix}
  1 & 2 & 9 \\
  3 & 1 & 5 
 \end{bmatrix}
=
 \begin{bmatrix}
7 & 4 & 19 \\
4 &	8 & 36 \\
31 & 22 & 103
 \end{bmatrix}
$$

$$
c_{11} = 1 \bullet 1 + 2 \bullet 3 = 1 + 6 = 7 \\
c_{12} = 1 \bullet 2 + 2 \bullet 1 = 2 + 2 = 4 \\
c_{13} = 1 \bullet 9 + 2 \bullet 5 = 9 + 10 = 19 \\
c_{21} = 4 \bullet 1 + 0 \bullet 3 = 4 + 0 = 4 \\
c_{22} = 4 \bullet 2 + 0 \bullet 1 = 8 + 0 = 8 \\
c_{23} = 4 \bullet 9 + 0 \bullet 5 = 36 + 0 = 36 \\
c_{31} = 7 \bullet 1 + 8 \bullet 3 = 7 + 24 = 31 \\
c_{32} = 7 \bullet 2 + 8 \bullet 1 = 14 + 8 = 22 \\
c_{33} = 7 \bullet 9 + 8 \bullet 5 = 63 + 40 = 103
$$

Вычислите, по возможности не используя программирование: $(5Е)^{–1}$, где Е – единичная матрица размера 5х5.

$$
 5E=\begin{bmatrix}
  5 & 0 & 0 & 0 & 0 \\
  0 & 5 & 0 & 0 & 0 \\
  0 & 0 & 5 & 0 & 0 \\
  0 & 0 & 0 & 5 & 0 \\
  0 & 0 & 0 & 0 & 5
 \end{bmatrix}
$$

Матрица натуральная. Для возведения в степень -1 воспользуемся свойством диагональных матриц. Обратная матрица так же является диагональной, при этом элементы на главной диагонали возводятся в -1 степень. Так же можно воспользоваться свойством натуральных матриц, и вынести $\frac{1}{5}$ за скобки.

$$
 (5E)^{-1}=
 \begin{bmatrix}
  \frac{1}{5} & 0 & 0 & 0 & 0 \\
  0 & \frac{1}{5} & 0 & 0 & 0 \\
  0 & 0 & \frac{1}{5} & 0 & 0 \\
  0 & 0 & 0 & \frac{1}{5} & 0 \\
  0 & 0 & 0 & 0 & \frac{1}{5}
 \end{bmatrix}
 =
 \frac{1}{5}\begin{bmatrix}
  1 & 0 & 0 & 0 & 0 \\
  0 & 1 & 0 & 0 & 0 \\
  0 & 0 & 1 & 0 & 0 \\
  0 & 0 & 0 & 1 & 0 \\
  0 & 0 & 0 & 0 & 1
 \end{bmatrix}
$$



## 5.2.
Вычислите определитель:  
$$
 \begin{bmatrix}
  1 & 2 & 3 \\
  4 & 0 & 6 \\
  7 & 8 & 9
 \end{bmatrix}
$$

$$
det A 
=
\begin{bmatrix}
1 & 2 & 3 \\
4 & 0 & 6 \\
7 & 8 & 9
\end{bmatrix}
=
1
\begin{bmatrix}
0 & 6 \\
8 & 9
\end{bmatrix}
-
2
\begin{bmatrix}
4 & 6 \\
7 & 9
\end{bmatrix}
+ 
3
\begin{bmatrix}
4 & 0 \\
7 & 8
\end{bmatrix}
$$

$$
1 \bullet (0\bullet9 - 6\bullet8)-2\bullet(4\bullet9 - 6\bullet7)+ 3\bullet(4\bullet8 -0\bullet7) = 60
$$

## 5.3.
1. Вычислите матрицу, обратную данной:
$$
 \begin{bmatrix}
  1 & 2 & 3 \\
  4 & 0 & 6 \\
  7 & 8 & 9
 \end{bmatrix}
$$

Посчитаем алгебраические дополнения для 1 строки.

$$
A_{11} = (-1)^{1+1}
\begin{bmatrix}
0 & 6 \\
8 & 9
\end{bmatrix}
=
0 \bullet 9 - 6 \bullet 8 = -48
$$

$$
A_{12} = (-1)^{1+2}
\begin{bmatrix}
4 & 6 \\
7 & 9
\end{bmatrix}
=
-1\bullet(4 \bullet 9) - (-1)\bullet(6 \bullet 7) = 6
$$

$$
A_{13} = (-1)^{1+3}
\begin{bmatrix}
4 & 0 \\
7 & 8
\end{bmatrix}
=
4 \bullet 8 - 0 \bullet 7 = 32
$$

Определитель матрицы:
$$
detA = 1*(-48) + 2*6 + 3 * 32 = 60
$$

Не равен нулю, обратная матрица существует. Считаем остальные алгебраические дополнения.


$$
A_{21} = (-1)^{2+1}
\begin{bmatrix}
2 & 3 \\
8 & 9
\end{bmatrix}
=
-1\bullet(2 \bullet 9) - (-1)\bullet(3 \bullet 8) = 6
$$

$$
A_{22} = (-1)^{2+2}
\begin{bmatrix}
1 & 3 \\
7 & 9
\end{bmatrix}
=
1 \bullet 9 - 3 \bullet 7 = -12
$$

$$
A_{23} = (-1)^{2+3}
\begin{bmatrix}
1 & 2 \\
7 & 8
\end{bmatrix}
=
-1\bullet(1 \bullet 8) - (-1)\bullet(2 \bullet 7) = 6
$$

$$
A_{31} = (-1)^{3+1}
\begin{bmatrix}
2 & 3 \\
0 & 6
\end{bmatrix}
=
2 \bullet 6) - 3 \bullet 0 = 12
$$

$$
A_{32} = (-1)^{3+2}
\begin{bmatrix}
1 & 3 \\
4 & 6 \\
\end{bmatrix}
=
-1\bullet(1 \bullet 6) - (-1)\bullet(3 \bullet 4) = 6
$$

$$
A_{33} = (-1)^{3+3}
\begin{bmatrix}
1 & 2 \\
4 & 0
\end{bmatrix}
=
1 \bullet 0 - 2 \bullet 4 = -8
$$

$$
A^{-1} = A_*^T /detA = 
\frac{1}{60} \bullet
\begin{bmatrix}
-48 & 6 & 12 \\
6 & -12 & 6 \\
32 & 6 & -8
 \end{bmatrix}
=
\begin{bmatrix}
  -\frac{4}{5} & \frac{1}{10} & \frac{1}{5} \\
  \frac{1}{10} & -\frac{1}{5} & \frac{1}{10} \\
  \frac{8}{15} & \frac{1}{10} & -\frac{2}{15}
 \end{bmatrix}
$$

2. Приведите пример матрицы 4х4, ранг которой равен 1.

$$
\begin{bmatrix}
3 & 1 & 2 & 3 \\
6 & 2 & 4 & 6 \\
3 & 1 & 2 & 3 \\
6 & 2 & 4 & 6 
\end{bmatrix}
$$

In [3]:
import numpy as np
a = np.array([[3, 1, 2, 3], [6, 2, 4, 6], [3, 1, 2, 3], [6, 2, 4, 6]])
np.linalg.matrix_rank(a)

1

Первым объемным (в данном, одномерном, случае - имеющим длину) минором для данной матрицы будет $$
\begin{bmatrix}
3 & 1\\
\end{bmatrix}
$$
Все остальные столбцы и строки могут быть выражены через него
$$
\begin{bmatrix}
3 & 1\\
3*2 & 1*2 \\
\end{bmatrix}
$$
 И так далее, до получения матрицы любого размера.

In [4]:
a = np.array([[3, 1], [6, 2]])
np.linalg.matrix_rank(a)

1

## 5.4.
Вычислите скалярное произведение двух векторов:  
(1, 5)  и  (2, 8)

$1 \bullet 2 + 5 \bullet 8 = 42$

## 5.5
Вычислите смешанное произведение трех векторов:
(1, 5, 0), (2, 8, 7) и (7, 1.5, 3) 

$$
\bar{a} = (1 , 5, 0) \\
\bar{b} = (2, 8, 7)  \\
\bar{c} = (7, 1.5, 3) \\
$$

$$
\bar{a} \times \bar{b} = \bar{i}(5 \bullet 7 - 0 \bullet 8)-\bar{j}(1 \bullet 7 - 0 \bullet 2)+\bar{k}(1 \bullet 8 - 5 \bullet 2) = 35\bar i - 7\bar{j} -2 \bar{k}
$$

$$
35 \bullet 7 + (-7) \bullet 1.5 + (-2) \bullet 3 =228.5
$$

## Решение систем линейных уравнений

1. Решите линейную систему:

$$
\begin{bmatrix}
  1 & 2 & 3 \\
  4 & 0 & 6 \\
  7 & 8 & 9
 \end{bmatrix} \cdot \begin{bmatrix}
  {x} \\
  {y} \\
  {z}
 \end{bmatrix} =   \begin{bmatrix}
  12 \\
  2 \\
  1
 \end{bmatrix} 
$$


In [51]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

2. Найдите псевдорешение:

$$
\begin{cases}
x + 2y – z = 1 \\
3x – 4y = 7 \\
8x – 5y + 2z = 12 \\
2x – 5z = 7 \\
11x +4y – 7z = 15 \\
\end{cases}
$$

Запишем в матричном виде:
$$
\begin{bmatrix}
  1 & 2 & -1 \\
  3 & -4 & 0 \\
  8 & -5 & 2 \\
  2 & 0 & -5 \\
  11 & 4 & -7
 \end{bmatrix} \cdot \begin{bmatrix}
  {x} \\
  {y} \\
  {z}
 \end{bmatrix} =   \begin{bmatrix}
  1 \\
  7 \\
  12 \\
  7 \\
  1
 \end{bmatrix} 
$$

In [53]:
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array([1, 7, 12, 7, 1])
np.linalg.lstsq(A, B)

# print(x,y, z)

/home/oem/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([ 0.33901371, -1.89529296, -0.89117382]),
 array([23.17471502]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

3. Сколько решений имеет линейная система:


$$
\begin{bmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6 \\
  7 & 8 & 9
 \end{bmatrix} \cdot \begin{bmatrix}
  {x} \\
  {y} \\
  {z}
 \end{bmatrix} =   \begin{bmatrix}
  12 \\
  2 \\
  1
 \end{bmatrix} 
$$

In [46]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([12, 2, 1])


In [47]:
np.linalg.matrix_rank(A, 0.0001)

2

Видим, что ранг матрицы меньше количества неизвестных. Система недоопределена.

Чтобы подобрать вектор B Например, сожно положить все его составлябщие нулем. Тогда все прямые пройдут через начало координат, и система будет иметь точное решение в этой точке.

In [48]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([0, 0, 0])
np.linalg.solve(A, B)

array([ 0.,  0., -0.])

4. Вычислите LU-разложение матрицы:
;;
\begin{bmatrix}
  1 & 2 & 3 \\
  2 & 16 & 21 \\
  4 & 28 & 73
 \end{bmatrix}
;;


In [56]:
A = np.array([ [1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)

print(P)
print(L)
print(U)

print(np.dot(P.transpose(), A) - np.dot(L, U))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.

Логичнее "решать" в обратном порядке.Сначала выберем корни, потом - рассчитаем вектор B, при котором система будет решаться.

Для простоты, примем x=y=z=1

$$
B=\begin{bmatrix}
  6 \\
  39 \\
  105
 \end{bmatrix} 
$$



In [57]:
B = np.array([6, 39, 105])
np.linalg.solve(A, B)

array([1., 1., 1.])

5. Найдите нормальное псевдорешение недоопределенной системы:
$$
\begin{cases}x + 2y – z = 1\\8x – 5y + 2z = 12\end{cases}
$$


Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум. 
